#!/bin/bash

mkdir -p /Users/nsergeant/.config/alacritty
mkdir -p /Users/nsergeant/.config/ctags
mkdir -p /Users/nsergeant/.config/karabiner

ln -sn /Users/nsergeant/Sources/dotfiles/nvim /Users/nsergeant/.config/nvim

ln -sf /Users/nsergeant/Sources/dotfiles/alacritty.toml /Users/nsergeant/.config/alacritty/alacritty.toml
ln -sf /Users/nsergeant/Sources/dotfiles/ctags.ctags /Users/nsergeant/.config/ctags/ctags.ctags
ln -sf /Users/nsergeant/Sources/dotfiles/gitignore /Users/nsergeant/.gitignore
ln -sf /Users/nsergeant/Sources/dotfiles/karabiner.edn /Users/nsergeant/.config/karabiner.edn
ln -sf /Users/nsergeant/Sources/dotfiles/karabiner.json /Users/nsergeant/.config/karabiner/karabiner.json
ln -sf /Users/nsergeant/Sources/dotfiles/tmux.conf /Users/nsergeant/.tmux.conf
ln -sf /Users/nsergeant/Sources/dotfiles/zshrc /Users/nsergeant/.zshrc

ln -sf /Users/nsergeant/Sources/dotfiles/vscode/settings.json /Users/nsergeant/Library/Application\ Support/Cursor/User/settings.json
ln -sf /Users/nsergeant/Sources/dotfiles/vscode/keybindings.json /Users/nsergeant/Library/Application\ Support/Cursor/User/keybindings.json

echo ✅ Done
