#!/bin/bash

ln -sf /Users/nsergeant/Sources/dotfiles/ctags /Users/nsergeant/.ctags
ln -sf /Users/nsergeant/Sources/dotfiles/eslintrc.json /Users/nsergeant/Code/.eslintrc.json
ln -sf /Users/nsergeant/Sources/dotfiles/eslintrc.json /Users/nsergeant/Coden/.eslintrc.json
ln -sf /Users/nsergeant/Sources/dotfiles/gitconfig /Users/nsergeant/.gitconfig
ln -sf /Users/nsergeant/Sources/dotfiles/gitignore /Users/nsergeant/.gitignore
ln -sf /Users/nsergeant/Sources/dotfiles/gvimrc /Users/nsergeant/.gvimrc
ln -sf /Users/nsergeant/Sources/dotfiles/karabiner.json /Users/nsergeant/.config/karabiner/karabiner.json
ln -sf /Users/nsergeant/Sources/dotfiles/noop /Users/nsergeant/.vimrc-env
ln -sf /Users/nsergeant/Sources/dotfiles/noop /Users/nsergeant/.zshrc-env
ln -sf /Users/nsergeant/Sources/dotfiles/prettier.config.js /Users/nsergeant/Code/prettier.config.js
ln -sf /Users/nsergeant/Sources/dotfiles/prettier.config.js /Users/nsergeant/Coden/prettier.config.js
ln -sf /Users/nsergeant/Sources/dotfiles/tmux-mac.conf /Users/nsergeant/.tmux.conf
ln -sf /Users/nsergeant/Sources/dotfiles/vimrc /Users/nsergeant/.vimrc
ln -sf /Users/nsergeant/Sources/dotfiles/zshrc /Users/nsergeant/.zshrc
