#!/bin/bash

mkdir -p /home/nick/.config/fontconfig
mkdir -p /home/nick/.config/i3
mkdir -p /home/nick/.fonts

ln -sf /home/nick/Sources/dotfiles/Xmodmap /home/nick/.Xmodmap
ln -sf /home/nick/Sources/dotfiles/Xresources /home/nick/.Xresources
ln -sf /home/nick/Sources/dotfiles/compton.conf /home/nick/.compton.conf
ln -sf /home/nick/Sources/dotfiles/config/chrome-flags.conf /home/nick/.config/chrome-flags.conf
ln -sf /home/nick/Sources/dotfiles/config/fontconfig/fonts.conf /home/nick/.config/fontconfig/fonts.conf
ln -sf /home/nick/Sources/dotfiles/config/gtk-3.0/gtk.css /home/nick/.config/gtk-3.0/gtk.css
ln -sf /home/nick/Sources/dotfiles/config/i3/battery /home/nick/.config/i3/battery
ln -sf /home/nick/Sources/dotfiles/config/i3/config /home/nick/.config/i3/config
ln -sf /home/nick/Sources/dotfiles/config/i3/i3blocks.conf /home/nick/.config/i3/i3blocks.conf
ln -sf /home/nick/Sources/dotfiles/config/i3/mail /home/nick/.config/i3/mail
ln -sf /home/nick/Sources/dotfiles/config/i3/weather /home/nick/.config/i3/weather
ln -sf /home/nick/Sources/dotfiles/config/redshift.conf /home/nick/.config/redshift.conf
ln -sf /home/nick/Sources/dotfiles/gitconfig /home/nick/.gitconfig
ln -sf /home/nick/Sources/dotfiles/gitignore /home/nick/.gitignore
ln -sf /home/nick/Sources/dotfiles/gvimrc /home/nick/.gvimrc
ln -sf /home/nick/Sources/dotfiles/tmux.conf /home/nick/.tmux.conf
ln -sf /home/nick/Sources/dotfiles/vimrc /home/nick/.vimrc
ln -sf /home/nick/Sources/dotfiles/wallpaper.jpg /home/nick/.wallpaper.jpg
ln -sf /home/nick/Sources/dotfiles/xbindkeysrc /home/nick/.xbindkeysrc
ln -sf /home/nick/Sources/dotfiles/xinitrc /home/nick/.xinitrc
ln -sf /home/nick/Sources/dotfiles/xprofile /home/nick/.xprofile
ln -sf /home/nick/Sources/dotfiles/zshrc /home/nick/.zshrc
sudo ln -sf /home/nick/Sources/dotfiles/etc/udev/rules.d/90-backlight.rules /etc/udev/rules.d/90-backlight.rules
sudo ln -sf /home/nick/Sources/dotfiles/etc/sysctl.d/99-sysctl.conf /etc/sysctl.d/99-sysctl.conf

chmod u+x /home/nick/.config/i3/battery
chmod u+x /home/nick/.config/i3/mail
chmod u+x /home/nick/.config/i3/weather
