#!/bin/bash

mkdir -p /home/nsergeant/.config/fontconfig
mkdir -p /home/nsergeant/.config/gtk-2.0
mkdir -p /home/nsergeant/.config/i3
mkdir -p /home/nsergeant/.fonts

ln -sf /home/nsergeant/Sources/dotfiles/Xmodmap /home/nsergeant/.Xmodmap
ln -sf /home/nsergeant/Sources/dotfiles/Xresources /home/nsergeant/.Xresources
ln -sf /home/nsergeant/Sources/dotfiles/compton.conf /home/nsergeant/.compton.conf
ln -sf /home/nsergeant/Sources/dotfiles/ctags /home/nsergeant/.ctags
ln -sf /home/nsergeant/Sources/dotfiles/config/chrome-flags.conf /home/nsergeant/.config/chrome-flags.conf
ln -sf /home/nsergeant/Sources/dotfiles/config/fontconfig/fonts.conf /home/nsergeant/.config/fontconfig/fonts.conf
ln -sf /home/nsergeant/Sources/dotfiles/config/gtk-2.0/gtkfilechooser.ini /home/nsergeant/.config/gtk-2.0/gtkfilechooser.ini
ln -sf /home/nsergeant/Sources/dotfiles/config/gtk-3.0/gtk.css /home/nsergeant/.config/gtk-3.0/gtk.css
ln -sf /home/nsergeant/Sources/dotfiles/config/i3/battery /home/nsergeant/.config/i3/battery
ln -sf /home/nsergeant/Sources/dotfiles/config/i3/config /home/nsergeant/.config/i3/config
ln -sf /home/nsergeant/Sources/dotfiles/config/i3/i3blocks.conf /home/nsergeant/.config/i3/i3blocks.conf
ln -sf /home/nsergeant/Sources/dotfiles/config/i3/mail /home/nsergeant/.config/i3/mail
ln -sf /home/nsergeant/Sources/dotfiles/config/i3/weather /home/nsergeant/.config/i3/weather
ln -sf /home/nsergeant/Sources/dotfiles/config/libinput-gestures.conf /home/nsergeant/.config/libinput-gestures.conf
ln -sf /home/nsergeant/Sources/dotfiles/config/mimeapps.list /home/nsergeant/.config/mimeapps.list
ln -sf /home/nsergeant/Sources/dotfiles/config/mimeapps.list /home/nsergeant/.local/share/applications/mimeapps.list
ln -sf /home/nsergeant/Sources/dotfiles/config/redshift.conf /home/nsergeant/.config/redshift.conf
ln -sf /home/nsergeant/Sources/dotfiles/fonts/Menlo-ForPowerline.ttc /home/nsergeant/.fonts/Menlo-ForPowerline.ttc
ln -sf /home/nsergeant/Sources/dotfiles/fonts/fontawesome-webfont.ttf /home/nsergeant/.fonts/fontawesome-webfont.ttf
ln -sf /home/nsergeant/Sources/dotfiles/gitconfig /home/nsergeant/.gitconfig
ln -sf /home/nsergeant/Sources/dotfiles/gitignore /home/nsergeant/.gitignore
ln -sf /home/nsergeant/Sources/dotfiles/gvimrc /home/nsergeant/.gvimrc
ln -sf /home/nsergeant/Sources/dotfiles/tmux-linux.conf /home/nsergeant/.tmux.conf
ln -sf /home/nsergeant/Sources/dotfiles/vimrc /home/nsergeant/.vimrc
ln -sf /home/nsergeant/Sources/dotfiles/vimrc-linux /home/nsergeant/.vimrc-env
ln -sf /home/nsergeant/Sources/dotfiles/wallpaper.png /home/nsergeant/.wallpaper.png
ln -sf /home/nsergeant/Sources/dotfiles/xbindkeysrc /home/nsergeant/.xbindkeysrc
ln -sf /home/nsergeant/Sources/dotfiles/xinitrc /home/nsergeant/.xinitrc
ln -sf /home/nsergeant/Sources/dotfiles/zshrc /home/nsergeant/.zshrc
ln -sf /home/nsergeant/Sources/dotfiles/zshrc-linux /home/nsergeant/.zshrc-env
sudo ln -sf /home/nsergeant/Sources/dotfiles/etc/X11/xorg.conf.d/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf
sudo ln -sf /home/nsergeant/Sources/dotfiles/etc/sysctl.d/99-sysctl.conf /etc/sysctl.d/99-sysctl.conf
sudo ln -sf /home/nsergeant/Sources/dotfiles/etc/systemd/system/suspend@.service /etc/systemd/system/suspend@.service
sudo ln -sf /home/nsergeant/Sources/dotfiles/etc/udev/rules.d/90-backlight.rules /etc/udev/rules.d/90-backlight.rules

chmod u+x /home/nsergeant/.config/i3/battery
chmod u+x /home/nsergeant/.config/i3/mail
chmod u+x /home/nsergeant/.config/i3/weather
